# ./Taskfile.yaml
# See: https://taskfile.dev/api/  

version: "3"  

tasks:  
  default:
    cmds:  
      - task: api  
  api:
    desc: "Start api-gateway service"
    cmds:
      - go run ./cmd/api-gateway --config=./config/dev.yaml

  test:
    desc: "Run tests"
    cmds:
      - go test -v ./tests
  bench:
    desc: "Run benchmarks"
    cmds:
      - go test -bench=. -benchmem ./tests

  docker-build:
    aliases:
      - build
    cmds:
      - docker build -t api-gateway:dev . 
  docker-run:
    aliases:
      - run
    cmds:
      - docker run -p 8080:8080 api-gateway:dev 